name: bones_ui
description: Bones_UI - An intuitive and user-friendly Web User Interface framework for Dart.
version: 3.0.0-beta.19
homepage: https://github.com/Colossus-Services/bones_ui

environment:
  sdk: '>=3.6.0 <4.0.0'

executables:
  bones_ui:
  bones_ui_test:

dependencies:
  js_interop_utils: ^1.0.9
  web_utils: ^1.0.18
  web: ^1.1.1
  intl_messages: ^3.0.0-beta.1
  dom_tools: ^3.0.0-beta.13
  dom_builder: ^3.0.0-beta.6
  swiss_knife: ^3.3.3
  statistics: ^1.2.0
  mercury_client: ^2.3.0
  dynamic_call: ^2.0.1
  project_template: ^1.1.1
  resource_portable: ^3.1.2
  extended_type: ^2.1.1
  expressions: ^0.2.5+3
  html_unescape: ^2.0.0
  intl: ^0.20.2
  yaml: ^3.1.3
  archive: ^4.0.7
  collection: ^1.19.1
  args: ^2.7.0
  logging: ^1.3.0
  path: ^1.9.1
  test: ^1.28.0
  test_api: ^0.7.8
  test_core: ^0.6.14
  stream_channel: ^2.1.4
  stack_trace: ^1.12.1


dev_dependencies:
  build_web_compilers: ^4.4.3
  build_runner: ^2.10.4
  lints: ^5.1.1
  dependency_validator: ^5.0.3


#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  dynamic_call:
#    path: ../dynamic_call
#  mercury_client:
#    path: ../mercury_client
#  intl_messages:
#    path: ../intl_messages
#  amdjs:
#    path: ../amdjs.dart
#  dom_builder:
#    path: ../dom_builder
#  dom_tools:
#    path: ../dom_tools
#  js_interop_utils:
#    path: ../js_interop_utils
#  web_utils:
#    path: ../web_utils
#  json_render:
#    path: ../json_render
#  json_object_mapper:
#    path: ../json_object_mapper
